{
    "name": "Hospital",
    "summary": "Управління лікарнею та аналітика візитів",
    "version": "19.0.5.0.0",
    "category": "Human Resources",
    "author": "xvbeb",
    "license": "AGPL-3",
    "depends": ["base", "web"],
    "images": ["static/description/icon.png"],
    "data": [
        "security/ir.model.access.csv",
        "data/hospital_doctor_category_data.xml",
        "data/hospital_disease_data.xml",
        "views/hospital_doctor_category_views.xml",
        "views/hospital_doctor_history_views.xml",
        "views/hospital_disease_views.xml",
        "views/hospital_doctor_views.xml",
        "views/hospital_patient_views.xml",
        "views/hospital_patient_visit_views.xml",
        "wizard/mass_reassign_doctor_wizard_views.xml",
        "wizard/visit_report_wizard_views.xml",
        "wizard/disease_month_report_wizard_views.xml",
        "report/hospital_doctor_report.xml",
        "views/hr_hospital_menus.xml",
    ],
    "demo": [
        "demo/hospital_doctor_demo.xml",
        "demo/hospital_patient_demo.xml",
        "demo/hospital_doctor_history_demo.xml",
        "demo/hospital_disease_demo.xml",
        "demo/hospital_patient_visit_demo.xml",
    ],
    "application": True,
    "installable": True,
}
